---
title: "0-Create_Species_Lookup_Table"
format: html
editor: visual
---

```{r, include = F}
require(tidyverse)
require(readxl)
require(writexl)
```


### Define which year of TreeMap you want to use
```{r}
tm_year <- 2022 # Options = 2016, 2020, 2022
```


## Load TreeMap tree tables
```{r}
treemap_dir <- "~/../../Data_heavy_projects/Forest_QM_automation/data/TreeMap"
trees16file <- file.path(treemap_dir, "TreeMap2016/TreeMap2016_tree_table.csv")
trees20file <- file.path(treemap_dir, "TreeMap2016/TreeMap2016_tree_table.csv")
trees22file <- file.path(treemap_dir, "TreeMap2022/TreeMap2022_CONUS_Tree_Table.csv")
```

Only load the TM vintage you need because it is slow to load
```{r}
if(tm_year == 2016){
  trees16 <- read.csv(trees16file, colClasses = c("character", "character"))
  tm_trees <- trees16 %>% 
    rename(TM_ID = tm_id)
} else if(tm_year == 2020){
  trees20 <- read.csv(file = trees20file, colClasses = c("character", "character"))
  tm_trees <- trees20 %>% 
    rename(TM_ID = tm_id)
} else if(tm_year == 2022){
  trees22 <-  read.csv(file = trees22file, colClasses = c("character", "character"))
  tm_trees <- trees22
} else{
  print("ERROR: Not a valid TreeMap year")
}
```

# Pull out species codes and numbers
```{r}
df <- tm_trees %>% 
  select(SPCD, COMMON_NAME, SCIENTIFIC_NAME, SPECIES_SYMBOL) %>% 
  distinct() %>% 
  arrange(SPCD)
```

# Save
```{r}
file_name <- "~/../../Data_heavy_projects/Forest_QM_automation/data/TreeMap/species_codes.xlsx"
write_xlsx(df, file_name)
```

