---
title: "5. Calculate carbon results from FVS output - Reforestation"
author: "Carmen Tubbesing"
date: "`r Sys.Date()`"
format: 
  html:
    embed-resources: TRUE
    toc: TRUE
---

```{r, include = F}
source("project_vars.R", local = TRUE)
```

```{r, include = F}
source("treatment_vars.R", local = TRUE)
```

# This run is for project `r proj_name`
## TCN = `r TCN`

```{r, include = F}
require(tidyverse)
require(readxl)
require(ggplot2)
```

## Load the FVS output files
```{r}
fvs_output_file <- paste(project_ID, TCN, "RF", sep = "_")
fvs_output_file <- paste0(fvs_output_dir, project_ID, "/", fvs_output_file, ".xlsx")
fvs_output_file
df <- read_excel(fvs_output_file)
```

```{r}
df_means <- df %>% 
  group_by(Year) %>% 
  summarize(Aboveground_Total_Live = mean(Aboveground_Total_Live)) 
df_means <- df_means %>% 
  ungroup()
```


```{r}
ggplot(df_means) +
  geom_point(aes(x = Year, y = Aboveground_Total_Live)) +
  labs(
    y = "Live Aboveground Carbon (C)") +
  theme_minimal()
```


# Filter to last year of project
```{r}
df <- df %>% 
  filter(Year == end_year)
```

# Multiply by acres and calculate results
-  Calculate total ending year carbon for each scenario
-  Print results in the order they appear in `FRM_Calculator_Tool`
```{r}
df %>% 
  group_by(MgmtID) %>% 
  mutate(Total_C = (Aboveground_Total_Live + Belowground_Live + Belowground_Dead + Standing_Dead) * area_ac) %>% 
  select(MgmtID, Total_C)
```

