---
title: "Reformat form responses"
format: html
editor: visual
---

```{r, include = F}
require(tidyverse)
require(readxl)
require(writexl)
```

# Load form responses

```{r}
df <- read_excel("../../form_responses/Forest Restoration & Management QM Oct15 2025.xlsx")
```

# Define the question number within the fuels treatment section that asks which fuels treatment type

```{r}
fuels_question <- "What type of fuels reduction is this activity?"
```

# Identify key columns that tell you which project type exists

```{r}
id_q <- 14
reforestation_yn <- 18
reforestation_2 <- 33
reforestation_3 <- 48
pest_yn <- 64
biomass_yn <- 78
conservation_yn <- 94
fuel_yn <- 105
```

# Define function to create each of the six sub-data-frames

```{r}
convert_df <- function(df, row, col_min, col_max){
  df_new <- df[row, col_min:col_max] %>% t() %>% as_tibble()
  colnames(df_new) <- "Answer"
  df_new <- df_new %>% 
    mutate(Question = colnames(df[col_min:col_max])) %>% 
    select(Question, Answer)
  return(df_new)
}
```

# Transpose, clean, and write an excel file for each project

```{r}
for(i in 1:nrow(df)){
  id <- df[i, id_q] %>% unlist()
  if(is.na(id)){
    id <- df[i, "Project Name"]
  }
  print(unlist(id))
  df1 <- convert_df(df=df, row=i, 1, reforestation_yn-1)
  df2 <- convert_df(df=df, row=i, reforestation_yn, pest_yn-1)
  df3 <- convert_df(df=df, row=i, pest_yn, biomass_yn-1)
  df4 <- convert_df(df=df, row=i, biomass_yn, conservation_yn-1)
  df5 <- convert_df(df=df, row=i, conservation_yn, fuel_yn-1)
  df6 <- convert_df(df=df, row=i, fuel_yn, ncol(df))
  
  # Remove questions where the answer is NA for all 6 dfs
  dfs <- c("df1", "df2", "df3", "df4", "df5", "df6")
  for(j in 1:6){
      dfj <- get(dfs[j])
      dfj <- dfj[!is.na(dfj$Answer), ]
      assign(dfs[j], dfj)
  }
  
  unnecessary_qs <- c("ID", "Start time", "Email", "Name", "Last modified time")
  df1 <- df1 %>% 
    filter(!Question %in% unnecessary_qs)
  df6_remove <- which(grepl("Does your project contain additional fuel reduction treatments?", df6$Question))
  df6 <- df6[-df6_remove,]
    df6_remove <- which(grepl("Does your project include fuels reduction treatments?", df6$Question))
  df6 <- df6[-df6_remove,]

  
  # Write to excel
  file_name <- paste0("../../form_responses/", id, ".xlsx")
  sheets <- list("Project"=df1, 
                 "Reforestation" =df2, 
                 "Pest_management"=df3, 
                 "Biomass"=df4, 
                 "Conservation"=df5, 
                 "Fuels_Reduction"=df6)
  write_xlsx(sheets, file_name)
}
```
