---
title: "1. Intersect LEMMA and polygons"
author: "Carmen Tubbesing"
date: "`r Sys.Date()`"
format: 
  html:
    embed-resources: TRUE
    toc: TRUE
---

```{r setup, include=FALSE}
# Load required libraries
library(tidyverse)
library(readr)
library(dplyr)
library(fs)
library(sf)
library(terra)
library(mapview)
library(writexl)
library(viridisLite)

# Set global options for cleaner output
options(dplyr.width = Inf)
options(dplyr.print_max = 50)
```

## Setup

### Define folders

*Note:* Replace these with the folders on your desktop

```{r}
lemma_dir <- "~/Reference data"
lemma_path <- file.path(lemma_dir, "LEMMA")
trt_dir <- "~/CCI/QMs/Forest Health QM/Test runs/21-FH_MEU-041/shapefiles"
output_dir <- "~/CCI/QMs/Forest Health QM/Test runs/21-FH_MEU-041/spatial_outputs"
```

### List all the shapefiles in `trt_dir`
```{r}
# List all .shp files recursively
shapefiles <- list.files(
  path = trt_dir,
  pattern = "\\.shp$",
  full.names = TRUE,
  recursive = TRUE
)

# View the list
shapefiles

```

## For each shapefile in `trt_dir`, calculate the area of each value of LEMMA that intersects with that polygon and save as an excel file
```{r}
#| warning: false
# For all the shapefiles in `trt_dir`, clip LEMMA to their extent and save each clipped raster in `temp_dir`
map_list <- list()
lemma <- rast(lemma_path)
for (shp in shapefiles) {
  # Read shapefile
  v <- vect(shp)
  v <-project(v, crs(lemma))
  # Clip raster to extent & mask
  cropped <- crop(lemma, v)
  masked <- mask(cropped, v)
  masked <- as.polygons(masked)
  intersected <- intersect(v, masked) # This smooths the edges of raster pixels to the actual polygon boundaries

  full <- st_as_sf(intersected)
  base_name <- tools::file_path_sans_ext(basename(shp))
  map_name <- paste("map", base_name, sep = "_")
  
  map <- mapview(
    full,
    zcol = "LEMMA",        # column used for coloring
    layer.name = "Intersected LEMMA", alpha = 1
    ) +
    mapview(v, col.regions = NA, col = "red", lwd = 2, alpha = 0.8, layer.name = "treatment")
  map_list[[map_name]] <- map
  
  full$area_m2 <- st_area(full)
  summary <- full %>% 
    st_drop_geometry() %>% 
    group_by(LEMMA) %>% 
    mutate(area_m2 = sum(as.numeric(area_m2))) %>% 
    mutate(Acres = area_m2/4046.8564) %>% 
    mutate(Total_Acres = sum(Acres)) %>%
    mutate(Sam_Wt = Acres/Total_Acres) %>%
    filter(Acres > 0) %>% 
    rename(Stand_ID = LEMMA) %>% 
    select(Stand_ID, Acres, Total_Acres, Sam_Wt)
  # Create an object based on shapefile name
  
  result_name <- paste(base_name, "areas", sep = "_")
  assign(result_name, summary)
  # Write as an excel file
  file_name <- paste(output_dir, "/", base_name, "_areas.xlsx", sep = "")
  write_xlsx(summary, file_name)
  message("Created: ", result_name)
  message("Wrote to: ", file_name)
}
```


# Plot each treatment individually
```{r, echo =FALSE}
print(names(map_list)[1])
map_list[[1]]
```

```{r, echo =FALSE}
print(names(map_list)[2])
map_list[[2]]
```


```{r, echo =FALSE}
print(names(map_list)[3])
map_list[[3]]
```

```{r, echo =FALSE}
print(names(map_list)[4])
map_list[[4]]
```

```{r, echo =FALSE}
print(names(map_list)[5])
map_list[[5]]
```

```{r, echo =FALSE}
print(names(map_list)[6])
map_list[[6]]
```
